### ISSUE TITLE
help getting started

### ISSUE THREAD

**Issue by fils** [zazuko/fuseki-geosparql#1]
First..  thanks so much for sharing your Dockerfile for building Jena with geosparql support.  

I am able to both pull and run and also rebuild the image with podman on Fedora.

When running I get the following:

```
(base) ➜  fuseki-geosparql git:(main) podman run -i --privileged  -v /home/fils/Containers/dvols/jena:/data -p 3030:3030 --rm a9e5420065a9
[opentelemetry.auto.trace 2022-01-21 16:50:08:092 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.2.0
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[fuseki 2022-01-21 16:50:09:375 +0000] [main] INFO org.apache.jena.fuseki.geosparql.Main {} - Arguments Received: [--loopback, false, -t, /fuseki/databases/ds, -t2, --validate, --default_geometry]
[fuseki 2022-01-21 16:50:09:411 +0000] [main] INFO org.apache.jena.fuseki.geosparql.DatasetOperations {} - Server Configuration: port=3030, datsetName=ds, loopbackOnly=false, updateAllowed=false, inference=false, applyDefaultGeometry=true, validateGeometryLiteral=true, convertGeoPredicates=false, removeGeoPredicates=false, queryRewrite=true, tdbFile=/fuseki/databases/ds, fileGraphFormats=[], fileGraphDelimiters=[], indexEnabled=true, indexSizes=[-1, -1, -1], indexExpiries=[5000, 5000, 5000], spatialIndexFile=null, tdb2=true, help=false
[fuseki 2022-01-21 16:50:09:465 +0000] [main] INFO org.apache.jena.fuseki.geosparql.DatasetOperations {} - TDB Dataset: /fuseki/databases/ds, TDB2: true
[fuseki 2022-01-21 16:50:10:031 +0000] [main] INFO org.apache.jena.geosparql.configuration.GeoSPARQLOperations {} - Applying hasDefaultGeometry - Started
[fuseki 2022-01-21 16:50:10:079 +0000] [main] INFO org.apache.jena.geosparql.configuration.GeoSPARQLOperations {} - Applying hasDefaultGeometry - Completed
[fuseki 2022-01-21 16:50:10:185 +0000] [main] WARN org.apache.sis.system {} - The “SIS_DATA” environment variable is not set.
[fuseki 2022-01-21 16:50:10:351 +0000] [main] WARN org.apache.jena.fuseki.geosparql.DatasetOperations {} - Datset empty. Spatial Index not constructed. Server will require restarting after adding data and any updates to build Spatial Index.
[fuseki 2022-01-21 16:50:10:761 +0000] [Thread-4] INFO org.apache.jena.fuseki.geosparql.GeosparqlServer {} - GeoSPARQL Server: Running - Port: 3030, Dataset: /ds, Loopback Only: false,  Allow Update: false
[fuseki 2022-01-21 16:50:10:841 +0000] [Thread-4] INFO org.apache.jena.fuseki.Server {} - Start Fuseki (http=3030)
```

I see the updates are set to false which I can confirm with 

```
mc cat nas/issue31/summoned/invemarexpert//test.jsonld | jsonld format -q | curl -X PUT --header "Content-Type:application/n-quads" -d @- http://localhost:3030/ds/data
HTTP method not allowed: PUT : Read-only
```

So it seems the server is running and I can get the "read-only" warning when trying to load some data, which I expect. 

hitting:  http://localhost:3030/

results in ```Error 404: Not Found```

I do have config files and approaches that work for me with core Jena 4  (no geosparql) but I am not exactly sure where to mount and leverage my config files.  

Do you have some documentation on firing up the container with a mounted volume to allow setting up a read-write database that I could start to load in some geosparql enhanced RDF into?

Again.  thanks so much for this.   I was not able to get even close to this far with building in geosparql support!
Any help you can provide would be appreciated!

**Comment by ktk** [comment]
Can't comment on the error, my colleague @ludovicm67 might though. But just as a FYI, Andy is working on better integration into Fuseki. You might want to play with that, see https://issues.apache.org/jira/browse/JENA-2230

**Comment by ludovicm67** [comment]
Hi @fils! Thanks for showing interest in our Fuseki Docker image with GeoSPARQL support.
I was waiting that the 4.4.0 version of Apache Jena was released, which is now the case.

For context, we are using this Docker image for some read-only cases, so this was perfectly fitting our needs on that part.
But we really needed to have at some point a way to do some configuration using configuration files, which was not possible before this release.

I will spend some time in the next days on working on this Docker image to have it using the latest version of Apache Jena and see how to have something great in terms of configuration, and see what will be possible to do or not.
Everything will be documented, and I will give some updates here once I'm done.

**Comment by fils** [comment]
@ludovicm67 great news!
I'll be looking forward to seeing it soon and giving it a try!  Really appreciate you sharing this development work!

**Comment by ludovicm67** [comment]
Hi @fils! I worked on upgrading the Fuseki version and add support for the WebUI and configuration options.
It's now ready, and you can get some documentation in the `README.md` file.

Some more additional information about Fuseki with GeoSPARQL: https://jena.apache.org/documentation/geosparql/.

Can you give it a try?
Please ping me if something is unclear so that I can update the `README` file consequently.
If everything is fine, we can close this issue.

**Comment by fils** [comment]
@ludovicm67  exciting!  I will try and give it a try here this evening and report back!

**Comment by fils** [comment]
@ludovicm67 sorry for the delay in getting back to you.   Here is where I am at.

I can successfully build and run the repo.   However, I am having two issues.   First, using

```
(base) ➜  fuseki-geosparql git:(main) ✗ podman run -i --privileged  -e ADMIN_PASSWORD -v /home/fils/Containers/dvols/jena:/fuseki/databases -p 3030:3030 --rm ab1169ffb4f6

[otel.javaagent 2022-02-11 13:58:30:914 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.10.1
[fuseki 2022-02-11 13:58:32:847 +0000] [main] WARN org.apache.sis.system {} - The “SIS_DATA” environment variable is not set.
[fuseki 2022-02-11 13:58:33:415 +0000] [main] INFO org.apache.jena.fuseki.Server {} - Apache Jena Fuseki 4.4.0
[fuseki 2022-02-11 13:58:33:583 +0000] [main] INFO org.apache.jena.fuseki.Config {} - FUSEKI_HOME=/opt/fuseki
[fuseki 2022-02-11 13:58:33:583 +0000] [main] INFO org.apache.jena.fuseki.Config {} - FUSEKI_BASE=/fuseki
[fuseki 2022-02-11 13:58:33:619 +0000] [main] INFO org.apache.jena.fuseki.Config {} - Shiro file: file:///fuseki/shiro.ini
[fuseki 2022-02-11 13:58:34:427 +0000] [main] INFO org.apache.jena.geosparql.configuration.GeoSPARQLOperations {} - Applying GeoSPARQL Schema - Started
[fuseki 2022-02-11 13:58:34:438 +0000] [main] INFO org.apache.jena.geosparql.configuration.GeoSPARQLOperations {} - GeoSPARQL schema not applied to empty graph: default
[fuseki 2022-02-11 13:58:34:454 +0000] [main] INFO org.apache.jena.geosparql.configuration.GeoSPARQLOperations {} - Applying GeoSPARQL Schema - Completed
[fuseki 2022-02-11 13:58:34:473 +0000] [main] WARN org.apache.jena.geosparql.assembler.GeoAssembler {} - Dataset empty. Spatial Index not constructed. Server will require restarting after adding data and any updates to build Spatial Index.
[fuseki 2022-02-11 13:58:34:515 +0000] [main] WARN org.apache.jena.fuseki.server.EndpointSet {} - Redefining endpoint for query
[fuseki 2022-02-11 13:58:34:657 +0000] [main] INFO org.apache.jena.fuseki.Server {} - Configuration file: /fuseki/config.ttl
[fuseki 2022-02-11 13:58:34:658 +0000] [main] INFO org.apache.jena.fuseki.Server {} - Path = /ds
[fuseki 2022-02-11 13:58:34:658 +0000] [main] INFO org.apache.jena.fuseki.Server {} - System
[fuseki 2022-02-11 13:58:34:660 +0000] [main] INFO org.apache.jena.fuseki.Server {} -   Memory: 7.8 GiB
[fuseki 2022-02-11 13:58:34:660 +0000] [main] INFO org.apache.jena.fuseki.Server {} -   Java:   16.0.2
[fuseki 2022-02-11 13:58:34:660 +0000] [main] INFO org.apache.jena.fuseki.Server {} -   OS:     Linux 5.15.11-200.fc35.x86_64 amd64
[fuseki 2022-02-11 13:58:34:661 +0000] [main] INFO org.apache.jena.fuseki.Server {} -   PID:    1
[fuseki 2022-02-11 13:58:34:799 +0000] [main] INFO org.apache.jena.fuseki.Server {} - Started 2022/02/11 13:58:34 GMT on port 3030
``` 

I am using podman, but hopefully that is not introducing any issues.

following

```
ARG FUSEKI_BASE="/fuseki"
RUN mkdir -p "${FUSEKI_BASE}/databases" 
```

I mount /fuseki/databases but I never see any DB written to it.   

When loading I used:

```
(base) ➜  jena  curl -X PUT --header "Content-Type:application/n-triples" -d @edmotest.rdf http://localhost:3030/ds/data
{
  "count" : 25 ,
  "tripleCount" : 25 ,
  "quadCount" : 0
}
```

the server shows

```

[fuseki 2022-02-11 14:07:15:168 +0000] [qtp1320631496-42] INFO org.apache.jena.fuseki.Fuseki {trace_id=32ac39496717f14abd1e3fde252b5e78, span_id=91b323ea785a053a, trace_flags=01} - [14] PUT http://localhost:3030/ds/data
[fuseki 2022-02-11 14:07:15:178 +0000] [qtp1320631496-42] INFO org.apache.jena.fuseki.Fuseki {trace_id=32ac39496717f14abd1e3fde252b5e78, span_id=91b323ea785a053a, trace_flags=01} - [14] Body: Content-Length=3717, Content-Type=application/n-triples, Charset=null => N-Triples : Count=25 Triples=25 Quads=0
[fuseki 2022-02-11 14:07:15:181 +0000] [qtp1320631496-42] INFO org.apache.jena.fuseki.Fuseki {trace_id=32ac39496717f14abd1e3fde252b5e78, span_id=91b323ea785a053a, trace_flags=01} - [14] 200 OK (12 ms)
```

I modified the config file

```
...
<#service> rdf:type fuseki:Service;
  fuseki:name "ds";

  fuseki:serviceQuery               "query" ;    # SPARQL query service
  fuseki:serviceUpdate              "update" ;   # SPARQL update service
  fuseki:serviceUpload              "upload" ;   # Non-SPARQL upload service
  fuseki:serviceReadWriteGraphStore "data" ;     # SPARQL Graph store protocol (read and write)

  fuseki:endpoint [ fuseki:operation fuseki:query ; ];
  fuseki:endpoint [ fuseki:operation fuseki:query ; fuseki:name "sparql" ];
  fuseki:endpoint [ fuseki:operation fuseki:query ; fuseki:name "queryold" ];
  fuseki:endpoint [ fuseki:operation fuseki:gsp-r ; ];
  fuseki:endpoint [ fuseki:operation fuseki:gsp-r ; fuseki:name "get" ];

  fuseki:dataset <#ds> .
...
```

perhaps I did that wrong?


This is where I am at so far.  If you see anything I am doing wrong or have any guidance I would appreciate it.

Thanks
Doug

**Comment by fils** [comment]
Update.   It looks like I should be using POST, not PUT.  

Also, I still don't seem able to write to ds yet.  However if I log in and make a new database it does allow me to load and persist the triples.

**Comment by fils** [comment]
Update 2

```
podman run -i --privileged  -e ADMIN_PASSWORD -v rdfdata:/fuseki -p 3030:3030 --rm ab1169ffb4f6
```

is working better.  I can create a docker volume mount it and then copy in the config files to the /fuseki mount point.  This allows me to persist the data through booting.   I think I just need to modify the config files for my databases there and I should have a working approach.   

This might be nice too since I might be able to mount it read only to a public version and read write to a controlled version.  We will see.  

But I am getting closer.  :)

**Comment by ludovicm67** [comment]
@fils thanks for your feedback!

I updated the default configuration in the Docker image to have the default dataset `ds` stored in `/fuseki/databases/ds`. Previously it was in `/fuseki/ds`.

So you can mount a volume at `/fuseki/databases` to persist all your datasets.
You can edit the [configuration file](https://github.com/zazuko/fuseki-geosparql/blob/main/config/config.ttl) which is mounted at `/fuseki/config.ttl`.

What's great with Fuseki, is that you can easily configure new endpoints using the configuration file.
You can decide to have read-only endpoints that you can share with everyone, and read-write ones that requires a password for example.
To configure some restricted access, you can edit the [shiro.ini](https://github.com/zazuko/fuseki-geosparql/blob/main/config/shiro.ini) file.

Also, a thing to know is that the spatial index will only be built when Fuseki is starting.
If you do many changes in the dataset, a good thing can be to restart the instance, so that the spacial index is up-to-date and so you can expect better performances.

**Comment by fils** [comment]
@ludovicm67 Thanks for the update..  I'll pull the changes and work from that.  

I made good progress on testing and will report back with the new version.  

I was able to make a test database, load some RDF with spatial information and do a successful geosparql call!   So very happy with that.

**Comment by ludovicm67** [comment]
@fils can I close this issue or do you have any other related question?

**Comment by fils** [comment]
@ludovicm67 go ahead and close the issue.   I have a working build and I can do the mounts to persist between running the containers.   I might have a few questions about the direct layout of the directory and the config files but if I do I can open a new issue.   

Same re: the access control approaches you mention in your previous post.  I have no expectation of issues with that, just never configured that.   So I may get lost.  ;) 

For the scope of this issue though I am fine.

Thanks again for all your work on this and for sharing it!   Very much appreciated.

**Comment by ludovicm67** [comment]
@fils thanks for all of your feedback!

Yes, feel free to open any new issue if needed, this can also help others to use the Docker image :)
