### ISSUE TITLE
Missing dot in config file

### ISSUE THREAD

**Issue by MathiasVDA** [zazuko/fuseki-geosparql#19]
I think there is a missing dot at the end of this line:
https://github.com/zazuko/fuseki-geosparql/blob/a60b232a26bcc04d471f4306c057766931cbffb4/config/config.ttl#L6C1-L7C55

And the one after

**Comment by ludovicm67** [comment]
Hello @MathiasVDA,

Thanks for opening this issue.
The missing dots are not impacting the Fuseki behavior.
But I will create a PR to improve the formatting so that it gets fixed.
