### ISSUE TITLE
Warning The “SIS_DATA” environment variable is not set / or value is not an existing directory

### ISSUE THREAD

**Issue by g-vidal** [zazuko/fuseki-geosparql#30]
I have dowloaded and run successfully your docker but even after fresh builds with various changes in `Dockerfile` or added the option  `-e "SIS_DATA=/home/vidal/Logiciels/Apache/apache-sis-1.4/data/"` I keep at best getting the warning :

```shell
[main] WARN org.apache.sis.system {} - The SIS_DATA environment variable is defined, but the given “/opt/fuseki/data” value is not an existing directory.

# even if 
ll /opt/fuseki/data
total 12K
drwxr-xr-x 3 root   root   4,0K  7 déc.  16:16 ./
drwxrwxr-x 6 fuseki fuseki 4,0K  7 déc.  16:15 ../
drwxr-xr-x 3 root   root   4,0K  7 déc.  16:16 Databases/
```
I am not flent with docker nor Java, could you please help me find howyo use SIS resource
Thanks for this very usefull work.

**Comment by ludovicm67** [comment]
Hi @g-vidal!

This is how you can make it working:
1. Download Apache SIS (https://sis.apache.org/) ; this seems that you have done this already
2. Extract the content of the Zip file, and make sure it's mounted somewhere in the Docker image like `/apache-sis`
3. Set the following environment variables:
   - `PATH` to `"/apache-sis/bin:${JAVA_HOME}/bin:${PATH}"`
   - `SIS_DATA` to `"/apache-sis/data"`
   - `SIS_OPTS` to `"--encoding UTF-8"`
4. Download Apache Derby (https://db.apache.org/derby/) and put the jar into `/apache-sis/lib` (the direct link to the latest version for now is: https://repo1.maven.org/maven2/org/apache/derby/derby/10.17.1.0/derby-10.17.1.0.jar)

And then you should be able to start Fuseki without that warning.

If for your use-case you don't have the need for Apache SIS, you can safely ignore this warning.

**Comment by ludovicm67** [comment]
I did some work to include Apache SIS by default in the Docker image, so that no one get this warning anymore, and don't have to struggle on the way how to integrate it by their own.

I'm closing this issue ; everything is tracked in #31.
