### ISSUE TITLE
Add Apache SIS by default

### ISSUE THREAD

**Issue by ludovicm67** [zazuko/fuseki-geosparql#31]
Until now, users needed to add and configure Apache SIS by their own.
The goal would be to include it by default to provide a more out-of-the-box Docker image.

**Comment by ludovicm67** [comment]
Hi @g-vidal!
Yes, this is the expected behavior.
I created a pull request to include Apache SIS by default in the Docker image.
Once tests are OK, I will merge it and trigger a new release of the Docker image.
I will let you know.

**Comment by ludovicm67** [comment]
Hi @g-vidal!
The release went well.
You can now use this Docker image (and future versions of it ; `latest` is also up-to-date if you pull the image again using `docker pull ghcr.io/zazuko/fuseki-geosparql:latest`): `ghcr.io/zazuko/fuseki-geosparql:v3.3.0` and you will be able to use Apache SIS.

**Comment by g-vidal** [comment]
:+1: @ludovicm67 I have installed and runned it. It seems  before  for the fuseki part but for geosparql the `/ds`  is read only. It is not possible to add data.
I have tried to add permissions in `shiro.ini` like this one :
```shell
/ds/**/upload = authcBasic,user[admin]
```
rebuild the image with no effect 
I am not sure that the graphics interface works for geosparql  but I cannot find nor execute  CLI lines to upload a graph.

**Comment by ludovicm67** [comment]
Hi @g-vidal!

As stated in the README file (https://github.com/zazuko/fuseki-geosparql?tab=readme-ov-file#dataset) the default dataset is read-only.

The documentation (https://github.com/zazuko/fuseki-geosparql/tree/main/docs/administration-protocol) explains this limitation by the fact that the Fuseki HTTP Administration Protocol does not support GeoSPARQL features.

So in that case, you will need to create a TDB instance by hand using the tdb tools provided by Apache Jena, and start Fuseki on top of that dataset.

It is still possible to have a read-write instance if you change the configuration file (`config.ttl`) to use a non-geosparql dataset instead.

This is all what is possible in the current state using our Docker image.
I'm sorry to not be able to assist you further on your needs, but I'm sure you will find the required resources to have it working the way you want, by browsing the net.
