### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by MadsHolten** [zazuko/fuseki-geosparql#48]
I am new to geoSPARQL, so bare with me. I tried loading the test dataset and successfully ran the tests.

```sparql
ASK {
  <urn:test:geosparql:bern:geometry> geo:sfWithin <urn:test:geosparql:france:geometry> .
} 
```
Returns **false** which is correct

```sparql
ASK {
  <urn:test:geosparql:strasbourg:geometry> geo:sfWithin <urn:test:geosparql:france:geometry> .
} 
```
Returns **true** which is correct

However, the following query doesn't return any results. I would imagine that I can use geoSPARQL queries to list all entities within a region, close to a point etc? If I can only use it with ASK queries I don't see much use..

```sparql
SELECT * WHERE {
  ?s geo:sfWithin <urn:test:geosparql:france:geometry> .
} 
```

I also expected to get a result on the following query which I don't:

```sparql
ASK { 
  <urn:test:geosparql:bern:geometry> geof:nearby (46.9 7.4 100 unit:kilometer)
}
```

So what is supported and what is not? :)

**Comment by MadsHolten** [comment]
Just a quick update. I learned that typings of the literals are essential.

Works:
```sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT ?point
WHERE {
  BIND("POLYGON ((-64.8 32.3, -65.5 18.3, -80.3 25.2, -64.8 32.3))"^^geo:wktLiteral AS ?polygon)
  VALUES ?point { "POINT (-70.268555 25.522615)"^^geo:wktLiteral "POINT (-60.996094 24.846565)"^^geo:wktLiteral }
  FILTER(geof:sfWithin(?point, ?polygon))
}
```

Doesn't work:
```sparql
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>

SELECT ?point
WHERE {
  BIND("POLYGON ((-64.8 32.3, -65.5 18.3, -80.3 25.2, -64.8 32.3))" AS ?polygon)
  VALUES ?point { "POINT (-70.268555 25.522615)"^^geo:wktLiteral "POINT (-60.996094 24.846565)"^^geo:wktLiteral }
  FILTER(geof:sfWithin(?point, ?polygon))
}
```

**Comment by ludovicm67** [comment]
@MadsHolten Sorry for the late answer, I was away this week.
Great that you found how to get it working and documented it here!
So in case others are having the same issue as you, they can see how to get it working :)

I will close this issue, as you were able to have it working.
